<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class VehiculoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehiculos = [
            [
                'titulo' => 'TOYOTA Rav4 220H eCVT 4x2 Style',
                'combustible' => 'Hibrido',
                'marca_id' => 1,
                'modelo_id' => 3,
                'carroceria_id' => 3,
                'color_id' => 5,
                'ubicacion_id' => 17,
                'fabricacion' => '2024-12-12',
                'kilometros' => 1,
                'precio' => 564564,
                'description' => '|| Compra 100% Online || Contacta con nuestro Equipo ||',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 434,
                'garantia' => 1,
                'cambio' => 0,
                'num_puertas' => 5,
                'etiqueta_id' => 1,
                'iva' => 1,
                'cc' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'HONDA CR-V Elegance 4x4',
                'combustible' => 'Gasolina',
                'marca_id' => 2,
                'modelo_id' => 4,
                'carroceria_id' => 2,
                'color_id' => 3,
                'ubicacion_id' => 12,
                'fabricacion' => '2023-05-10',
                'kilometros' => 15000,
                'precio' => 32000,
                'description' => 'Vehículo impecable, revisado y garantizado.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 180,
                'garantia' => 1,
                'cambio' => 1,
                'num_puertas' => 5,
                'etiqueta_id' => 2,
                'iva' => 1,
                'cc' => 2000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Ford Mustang GT Fastback',
                'combustible' => 'Gasolina',
                'marca_id' => 3,
                'modelo_id' => 5,
                'carroceria_id' => 1,
                'color_id' => 1,
                'ubicacion_id' => 25,
                'fabricacion' => '2022-06-15',
                'kilometros' => 20000,
                'precio' => 55000,
                'description' => 'Potente deportivo, ideal para entusiastas.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 450,
                'garantia' => 1,
                'cambio' => 1,
                'num_puertas' => 2,
                'etiqueta_id' => 3,
                'iva' => 1,
                'cc' => 5000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'BMW X5 xDrive30d',
                'combustible' => 'Diesel',
                'marca_id' => 6,
                'modelo_id' => 6,
                'carroceria_id' => 4,
                'color_id' => 7,
                'ubicacion_id' => 8,
                'fabricacion' => '2023-01-20',
                'kilometros' => 10000,
                'precio' => 72000,
                'description' => 'SUV premium con excelentes prestaciones.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 265,
                'garantia' => 1,
                'cambio' => 1,
                'num_puertas' => 5,
                'etiqueta_id' => 4,
                'iva' => 1,
                'cc' => 3000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audi A4 Avant 40 TDI',
                'combustible' => 'Diesel',
                'marca_id' => 8,
                'modelo_id' => 7,
                'carroceria_id' => 5,
                'color_id' => 2,
                'ubicacion_id' => 15,
                'fabricacion' => '2022-03-18',
                'kilometros' => 50000,
                'precio' => 45000,
                'description' => 'Estilo, eficiencia y confort en un mismo coche.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 190,
                'garantia' => 0,
                'cambio' => 1,
                'num_puertas' => 5,
                'etiqueta_id' => 2,
                'iva' => 1,
                'cc' => 2000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Mercedes-Benz C-Class 220d',
                'combustible' => 'Diesel',
                'marca_id' => 7,
                'modelo_id' => 8,
                'carroceria_id' => 1,
                'color_id' => 4,
                'ubicacion_id' => 30,
                'fabricacion' => '2021-11-25',
                'kilometros' => 30000,
                'precio' => 38000,
                'description' => 'Lujo y potencia en un sedán elegante.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 194,
                'garantia' => 1,
                'cambio' => 1,
                'num_puertas' => 4,
                'etiqueta_id' => 4,
                'iva' => 1,
                'cc' => 2200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Volkswagen Golf GTI Performance',
                'combustible' => 'Gasolina',
                'marca_id' => 9,
                'modelo_id' => 9,
                'carroceria_id' => 1,
                'color_id' => 8,
                'ubicacion_id' => 5,
                'fabricacion' => '2022-08-12',
                'kilometros' => 15000,
                'precio' => 35000,
                'description' => 'Deportivo compacto con excelente rendimiento.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 245,
                'garantia' => 0,
                'cambio' => 1,
                'num_puertas' => 5,
                'etiqueta_id' => 3,
                'iva' => 1,
                'cc' => 2000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Hyundai Tucson Hybrid 1.6 TGDi',
                'combustible' => 'Hibrido',
                'marca_id' => 10,
                'modelo_id' => 10,
                'carroceria_id' => 3,
                'color_id' => 9,
                'ubicacion_id' => 20,
                'fabricacion' => '2023-09-05',
                'kilometros' => 8000,
                'precio' => 34000,
                'description' => 'SUV versátil con tecnología híbrida avanzada.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 230,
                'garantia' => 1,
                'cambio' => 1,
                'num_puertas' => 5,
                'etiqueta_id' => 5,
                'iva' => 1,
                'cc' => 1600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Nissan Qashqai DIG-T 140',
                'combustible' => 'Gasolina',
                'marca_id' => 5,
                'modelo_id' => 11,
                'carroceria_id' => 3,
                'color_id' => 10,
                'ubicacion_id' => 18,
                'fabricacion' => '2021-07-08',
                'kilometros' => 25000,
                'precio' => 25000,
                'description' => 'SUV compacto ideal para la ciudad y la carretera.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 140,
                'garantia' => 0,
                'cambio' => 1,
                'num_puertas' => 5,
                'etiqueta_id' => 3,
                'iva' => 1,
                'cc' => 1400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Chevrolet Camaro SS',
                'combustible' => 'Gasolina',
                'marca_id' => 4,
                'modelo_id' => 12,
                'carroceria_id' => 1,
                'color_id' => 6,
                'ubicacion_id' => 3,
                'fabricacion' => '2022-04-15',
                'kilometros' => 10000,
                'precio' => 70000,
                'description' => 'Puro músculo americano, una bestia en la carretera.',
                'imagen' => 'coche.png',
                'disponible' => 1,
                'user_id' => 1,
                'cv' => 455,
                'garantia' => 1,
                'cambio' => 1,
                'num_puertas' => 2,
                'etiqueta_id' => 4,
                'iva' => 1,
                'cc' => 6200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];


        // Inserta los vehículos en la base de datos
        DB::table('vehiculos')->insert($vehiculos);
    }
}
